# Generated by Django 4.1 on 2022-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='I am Fanilo, a developer from Onja Madagascar', editable=b'I00\n', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='About me', editable=b'I00\n', max_length=200),
        ),
    ]
